In [3]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier


In [4]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt


In [5]:
dataset = pd.read_csv("archive/heart.csv")
dataset.head()


age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [6]:
#Check for duplicate
dataset[dataset.duplicated()]

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
164   38    1   2     138   175    0        1       173     0      0.0    2   

     caa  thall  output  
164    4      2       1

In [7]:
#remove
dataset.drop_duplicates(keep='first',inplace=True)
dataset.shape

(302, 14)

In [8]:
#drop "output" for labeld data
#y = dataset["output"] 
#x = pd.DataFrame(dataset)
y = pd.DataFrame(dataset["output"])
x = dataset.drop(["output"], axis=1)

In [28]:
x

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2  
2      0      2  
3      0      2  
4      0      2  
..   ...    ...  
298    0      3  
299    0      3  
300    2      3  
301    1      3  
302    1      2  

[302 rows x 13 columns]

In [29]:
y

output
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[302 rows x 1 columns]

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer 

#transofrm pipeline
trans_pipeline = Pipeline([("imputer", SimpleImputer(strategy="median")), 
                           ("std_scaler", StandardScaler()),
    ])

x_prep = trans_pipeline.fit_transform(x)

In [31]:
print(f"shape data_set: {dataset.shape}", f"shape of x: {x.shape}" , f"shape of y: {y.shape}")

shape data_set: (302, 14) shape of x: (302, 13) shape of y: (302, 1)


Split dataset into training and testing sets

In [32]:
train_X, test_X, train_Y, test_Y = train_test_split(x_prep, y ,test_size=0.2, random_state=42)

In [33]:
train_X.shape, test_X.shape, train_Y.shape, test_Y.shape

((241, 13), (61, 13), (241, 1), (61, 1))

In [34]:
#train_x_tr = trans_pipeline.fit_transform(train_x)
#test_x_tr = trans_pipeline.fit_transform(test_x)
#train_x_tr.shape

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.base import clone
knn_clf = KNeighborsClassifier(n_neighbors=1)
knn_clf_clone = clone(knn_clf)

In [36]:
train_y = np.ravel(train_y)
knn_clf.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=1)

In [37]:
predict = knn_clf.predict(train_x)
predict

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1])

Feature Scaling
Ml algortihms dont peforme that good if u have big scaling between numerical attributes input 
How to get Aattributes to have the same scale: min max scaling, standardization

In [38]:
#Min max scaling (normalization) shift scaling to new_value = (value - min)/(max - min)
#Standardization is also an option.: substracts the mean value and divides it by the standard deation 

In [39]:

predict = lambda data_x : knn_clf.predict(data_x)
predict_value = predict(train_x)

In [40]:
#Using Cross-Validation to test for accuracy result
from sklearn.model_selection import cross_val_score

accuracy = cross_val_score(knn_clf, train_x, train_y, cv = 5)
accuracy

array([0.73469388, 0.77083333, 0.75      , 0.72916667, 0.79166667])

In [41]:
accuracy.sum()/len(accuracy) #durchschnittliche accuracy

0.7552721088435373

In [42]:
from sklearn.metrics import accuracy_score
predict = knn_clf.predict(train_x_tr)


NameError: name 'train_x_tr' is not defined

In [59]:
#Implement 5k_cross_validation
# copy train data and shuffle it 

import random 
fold_x = train_x.copy()
fold_y = train_y.copy()
random.seed(42)
random.shuffle(fold_x)
random.shuffle(fold_y)

fold_x, train_x

(array([[-1.3750206 ,  0.68265615,  0.0353515 , ...,  0.97951442,
         -0.71491124, -0.51399432],
        [-1.3750206 ,  0.68265615,  0.0353515 , ...,  0.97951442,
         -0.71491124, -0.51399432],
        [-1.3750206 ,  0.68265615,  0.0353515 , ...,  0.97951442,
         -0.71491124, -0.51399432],
        ...,
        [-0.04655495, -1.46486632,  0.0353515 , ...,  0.97951442,
          0.28003436, -0.51399432],
        [ 0.39626693,  0.68265615,  1.005911  , ..., -0.64583368,
         -0.71491124,  1.11996657],
        [-0.37867136, -1.46486632,  1.005911  , ...,  0.97951442,
          0.28003436, -0.51399432]]),
 array([[-1.3750206 ,  0.68265615,  0.0353515 , ...,  0.97951442,
         -0.71491124, -0.51399432],
        [ 1.50332164,  0.68265615,  1.005911  , ..., -0.64583368,
         -0.71491124,  1.11996657],
        [ 1.39261617,  0.68265615, -0.93520799, ..., -0.64583368,
          1.27497996,  1.11996657],
        ...,
        [ 1.61402711,  0.68265615,  1.97647049, ..., -

In [60]:
#Split data and put into list to iterate over 
def k_split(n : int, data_x, data_y):
    split_data_x = []
    split_data_y = []
    len_k = round(len(data_x)/n)
    for i in range(n-1):
        split_data_x.append(data_x[len_k*i:len_k*(i+1):])
        split_data_y.append(data_y[len_k*i:len_k*(i+1):])
    split_data_x.append(data_x[len_k*(n-1)::])
    split_data_y.append(data_y[len_k*(n-1)::])   
    
    return split_data_x, split_data_y

k_split(5, fold_x , fold_y)

([array([[-1.3750206 ,  0.68265615,  0.0353515 , -0.66171188,  0.9386903 ,
          -0.41844626,  0.90165655,  0.54363221, -0.69834428, -0.8995441 ,
           0.97951442, -0.71491124, -0.51399432],
         [-1.3750206 ,  0.68265615,  0.0353515 , -0.66171188,  0.9386903 ,
          -0.41844626,  0.90165655,  0.54363221, -0.69834428, -0.8995441 ,
           0.97951442, -0.71491124, -0.51399432],
         [-1.3750206 ,  0.68265615,  0.0353515 , -0.66171188,  0.9386903 ,
          -0.41844626,  0.90165655,  0.54363221, -0.69834428, -0.8995441 ,
           0.97951442, -0.71491124, -0.51399432],
         [ 0.06415052, -1.46486632,  0.0353515 ,  0.19375468,  0.06774054,
          -0.41844626, -1.0025412 ,  0.49989834, -0.69834428,  0.30784398,
          -0.64583368, -0.71491124, -0.51399432],
         [ 1.39261617,  0.68265615, -0.93520799, -0.37655636,  0.14515829,
           2.38979311,  0.90165655,  0.58736607, -0.69834428, -0.72706009,
          -0.64583368,  1.27497996,  1.11996657],


In [61]:
#Implement k_fold function

In [67]:
def k_fold(n: int , data_x , data_y):
    data_x, data_y = k_split(n, data_x, data_y)
    result = []
    for i in range(0,n):
        train_x, test_x , train_y , test_y = train_test_split(data_x[i], data_y[i] , test_size = 0.2, random_state=42)
        knn_clf_clone.fit(train_x, train_y)
        predicted = knn_clf.predict(test_x)
        correct_pred = sum(predicted == test_y)
        result.append(correct_pred/len(predicted))
    return result

k_fold(5, fold_x, fold_y)

[0.6, 0.6, 0.5, 0.5, 0.6]

In [47]:
# split into K=5 groups split training data into 5 Groups

Compare sklearn Cross validation vs mine. Did not use MSE, which should account for the difference 

In [72]:
from sklearn.model_selection import cross_val_score
train_Y = np.ravel(train_Y)
cross_val_score(knn_clf_clone, train_X, train_Y , cv=5 , scoring="accuracy")

array([0.73469388, 0.77083333, 0.75      , 0.72916667, 0.79166667])

In [ ]:
#fold_x_train, fold_x_test, fold_y_train, fold_y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
#k_fold_x = pd.DataFrame(fold_x_train)
#k_fold_x
#k_fold_y = pd.DataFrame(fold_y_train)

In [ ]:
#splitting data into K=5 parts, try to implement function to do this later
#training
#x_1 = k_fold_x.iloc[0:48]
#x_2 = k_fold_x.iloc[48:48*2]
#x_3 = k_fold_x.iloc[48*2: 48*3]
#x_4 = k_fold_x.iloc[48*3: 48*4]
#x_5 = k_fold_x.iloc[48*4:]

In [ ]:
#x_1.shape, x_2.shape, x_3.shape , x_4.shape , x_5.shape

In [ ]:
#training
#y_1 = k_fold_y.iloc[0:48]
#y_2 = k_fold_y.iloc[48:48*2]
#y_3 = k_fold_y.iloc[48*2: 48*3]
#y_4 = k_fold_y.iloc[48*3: 48*4]
#y_5 = k_fold_y.iloc[48*4:]

In [ ]:
#y_1, y_2, y_3, y_4, y_5 = np.array(y_1), np.array(y_2), np.array(y_3), np.array(y_4), np.array(y_5)

#y_1, y_2, y_3, y_4, y_5 = np.ravel(y_1),np.ravel(y_2),np.ravel(y_3),np.ravel(y_4),np.ravel(y_5),

In [ ]:
#test_k_x = [x_1,x_2,x_3,x_4,x_5]
#test_k_y = [y_1,y_2,y_3,y_4,y_5]


In [213]:
#def k_fold(x_train,y_train, k_folds):
    #results = []
    #knn_clf_fold = KNeighborsClassifier(n_neighbors=1)
    #for i in range(0,k_folds - 3):
        #knn_clf.fit(x_train[i],y_train[i])
        #predicted = knn_clf.predict(x_train[i])
        #results.append(accuracy_score(y_train[i+1], predicted))
    #return results

#k_fold(test_k_x,test_k_y,5)

In [214]:
#knn_clf_fold = KNeighborsClassifier(n_neighbors=1)
#knn_clf.fit(x_1,y_1)
#predicted = knn_clf.predict(x_1)
#ccuracy_score(y_4, predicted.round())

In [215]:
#knn_clf.fit(x_3,y_3)
#predicted = knn_clf.predict(x_3)
#accuracy_score(y_4, predicted.round())